' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' All rights reserved. This program and the accompanying materials are made available under the
' terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
' available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html

@startuml(id=CALYPSO_FULL)
package org.eclipse.keyple.calypso.command #FFFFFF {

package org.eclipse.keyple.calypso.command.po #FFFFFF {

abstract AbstractPoCommandBuilder {
  #CsmRevision defaultRevision = PoRevision.REV3_1
  +AbstractPoCommandBuilder(CalypsoPoCommands reference, ApduRequest request)
}

enum CalypsoPoCommands {
  PO_GET_DATA_FCI
  PO_OPEN_SESSION_24
  PO_OPEN_SESSION_31
  PO_OPEN_SESSION_32
  PO_CLOSE_SESSION
  PO_READ_RECORDS
  PO_UPDATE_RECORD
  PO_APPEND_RECORD
  PO_GET_CHALLENGE
}

enum PoRevision {
  REV2_4
  REV3_1
  REV3_2
}

interface PoSendableInSession
}
package org.eclipse.keyple.calypso.command.csm #FFFFFF {

abstract AbstractCsmCommandBuilder {
  #CsmRevision defaultRevision = CsmRevision.C1
  +AbstractCsmCommandBuilder(CalypsoSmCommands reference, ApduRequest request)
}

enum CalypsoSmCommands {
  CSM_SELECT_DIVERSIFIER
  CSM_GET_CHALLENGE
  CSM_DIGEST_INIT
  CSM_DIGEST_UPDATE
  CSM_DIGEST_UPDATE_MULTIPLE
  CSM_DIGEST_CLOSE
  CSM_DIGEST_AUTHENTICATE
}

enum CsmRevision {
  C1
  S1D
}

interface CsmSendableInSession
}

interface SendableInSession

CalypsoPoCommands "1" *-left-> "*" AbstractPoCommandBuilder : references
CalypsoSmCommands "1" *-left-> "*" AbstractCsmCommandBuilder : references

PoRevision "+1" -- "1..*" AbstractPoCommandBuilder
'CalypsoPoCommands "1" -left-> "1..*" AbstractPoCommandBuilder : references

CsmRevision "+1" -- "1..*" AbstractCsmCommandBuilder
'CalypsoSmCommands "1" -right-> "1..*" AbstractCsmCommandBuilder : references

SendableInSession <|-right- PoSendableInSession : extends
SendableInSession <|-right- CsmSendableInSession : extends

'CalypsoPoCommands -up[hidden]- SendableInSession
'CalypsoSmCommands -up[hidden]- SendableInSession
''PoRevision -left[hidden]- SendableInSession
''CsmRevision -right[hidden]- SendableInSession
PoRevision -left[hidden]- PoSendableInSession
CsmRevision -left[hidden]- CsmSendableInSession
}
@enduml

@startuml(id=CALYPSO_PO)
package org.eclipse.keyple.calypso.command.po #FFFFFF {

interface PoSendableInSession

package org.eclipse.keyple.calypso.command.po.builder #FFFFFF {

class ReadRecordsCmdBuild
class UpdateRecordCmdBuild
class OpenSessionCmdBuild
class CloseSessionCmdBuild

ReadRecordsCmdBuild -down[hidden]- UpdateRecordCmdBuild
UpdateRecordCmdBuild -down[hidden]- OpenSessionCmdBuild
OpenSessionCmdBuild -down[hidden]- CloseSessionCmdBuild

ReadRecordsCmdBuild .left.|> PoSendableInSession : implements
UpdateRecordCmdBuild .left.|> PoSendableInSession : implements
}

enum CalypsoPoCommands {
  PO_GET_DATA_FCI
  PO_OPEN_SESSION_24
  PO_OPEN_SESSION_31
  PO_OPEN_SESSION_32
  PO_CLOSE_SESSION
  PO_READ_RECORDS
  PO_UPDATE_RECORD
  PO_APPEND_RECORD
  PO_GET_CHALLENGE
}

package org.eclipse.keyple.calypso.command.po.parser #FFFFFF {
class PoFciRespPars
class OpenSessionRespPars
class ReadRecordsRespPars
class CloseSessionRespPars

PoFciRespPars -down[hidden]- OpenSessionRespPars
OpenSessionRespPars -down[hidden]- ReadRecordsRespPars
ReadRecordsRespPars -down[hidden]- CloseSessionRespPars
}

CalypsoPoCommands "1" *-left-> "1" OpenSessionCmdBuild : references
CalypsoPoCommands "1" *--> "1" ReadRecordsCmdBuild : references
CalypsoPoCommands "1" *--> "1" UpdateRecordCmdBuild : references
CalypsoPoCommands "1" *--> "1" CloseSessionCmdBuild : references

CalypsoPoCommands "1" *-right-> "1" PoFciRespPars : references
CalypsoPoCommands "1" *--> "1" OpenSessionRespPars : references
CalypsoPoCommands "1" *--> "1" ReadRecordsRespPars : references
CalypsoPoCommands "1" *--> "1" CloseSessionRespPars : references

abstract AbstractPoCommandBuilder {
  #CsmRevision defaultRevision = PoRevision.REV3_1
  +AbstractPoCommandBuilder(CalypsoPoCommands reference, ApduRequest request)
}

enum PoRevision {
  REV2_4
  REV3_1
  REV3_2
}

PoRevision "+1" -right- "1..*" AbstractPoCommandBuilder

OpenSessionCmdBuild --|> AbstractPoCommandBuilder : extends
ReadRecordsCmdBuild --|> AbstractPoCommandBuilder : extends
UpdateRecordCmdBuild --|> AbstractPoCommandBuilder : extends
CloseSessionCmdBuild --|> AbstractPoCommandBuilder : extends

org.eclipse.keyple.calypso.command.po.builder -down[hidden]- AbstractPoCommandBuilder
}
@enduml

@startuml(id=CALYPSO_SM)
package org.eclipse.keyple.calypso.command.csm #FFFFFF {

interface CsmSendableInSession

package org.eclipse.keyple.calypso.command.csm.builder #FFFFFF {

class PsoComputeSignatureCmdBuild
class PsoVerifySignatureCmdBuild
class SelectDiversifierCmdBuild
'class GetChallengeCmdBuild
class DigestInitCmdBuild
class DigestUpdateCmdBuild
'class DigestUpdateMultipleCmdBuild
'class DigestCloseCmdBuild
'class DigestAuthenticateCmdBuild

PsoComputeSignatureCmdBuild -down[hidden]- PsoVerifySignatureCmdBuild
PsoVerifySignatureCmdBuild -down[hidden]- SelectDiversifierCmdBuild
'SelectDiversifierCmdBuild -down[hidden]- GetChallengeCmdBuild
'GetChallengeCmdBuild -down[hidden]- DigestInitCmdBuild
SelectDiversifierCmdBuild -down[hidden]- DigestInitCmdBuild
DigestInitCmdBuild -down[hidden]- DigestUpdateCmdBuild
'DigestUpdateCmdBuild -down[hidden]- DigestUpdateMultipleCmdBuild
'DigestUpdateMultipleCmdBuild -down[hidden]- DigestCloseCmdBuild
'DigestUpdateCmdBuild -down[hidden]- DigestCloseCmdBuild
'DigestCloseCmdBuild -down[hidden]- DigestAuthenticateCmdBuild

'PsoComputeSignatureCmdBuild .down.|> CsmSendableInSession : implements
'PsoVerifySignatureCmdBuild .up.|> CsmSendableInSession : implements
PsoComputeSignatureCmdBuild .left.|> CsmSendableInSession : implements
PsoVerifySignatureCmdBuild .left.|> CsmSendableInSession : implements
}

enum CalypsoSmCommands {
  CSM_PSO_COMPUTE_SIGNATURE
  CSM_PSO_VERIFY_SIGNATURE
  CSM_SELECT_DIVERSIFIER
  CSM_GET_CHALLENGE
  CSM_DIGEST_INIT
  CSM_DIGEST_UPDATE
  CSM_DIGEST_UPDATE_MULTIPLE
  CSM_DIGEST_CLOSE
  CSM_DIGEST_AUTHENTICATE
}

package org.eclipse.keyple.calypso.command.csm.parser #FFFFFF {
class SelectDiversifierRespPars
class GetChallengeRespPars
class DigestUpdateRespPars

SelectDiversifierRespPars -down[hidden]- GetChallengeRespPars
GetChallengeRespPars -down[hidden]- DigestUpdateRespPars
}

CalypsoSmCommands "1" *-left-> "1" PsoComputeSignatureCmdBuild : references
'CalypsoSmCommands "1" *--> "1" PsoComputeSignatureCmdBuild : references
CalypsoSmCommands "1" *--> "1" PsoVerifySignatureCmdBuild : references
CalypsoSmCommands "1" *--> "1" SelectDiversifierCmdBuild : references
'CalypsoSmCommands "1" *--> "1" GetChallengeCmdBuild : references
CalypsoSmCommands "1" *--> "1" DigestInitCmdBuild : references
CalypsoSmCommands "1" *--> "1" DigestUpdateCmdBuild : references
'CalypsoSmCommands "1" *-left-> "1" DigestUpdateCmdBuild : references
'CalypsoSmCommands "1" *--> "1" DigestUpdateMultipleCmdBuild : references
'CalypsoSmCommands "1" *--> "1" DigestCloseCmdBuild : references
'CalypsoSmCommands "1" *--> "1" DigestAuthenticateCmdBuild : references

CalypsoSmCommands "1" *-right-> "1" SelectDiversifierRespPars : references
'CalypsoSmCommands "1" *--> "1" SelectDiversifierRespPars : references
CalypsoSmCommands "1" *--> "1" GetChallengeRespPars : references
'CalypsoSmCommands "1" *--> "1" DigestUpdateRespPars : references
'CalypsoSmCommands "1" *-right-> "1" DigestUpdateRespPars : references

'org.eclipse.keyple.calypso.command.csm.builder -right[hidden]- CalypsoSmCommands
'CalypsoSmCommands -right[hidden]- org.eclipse.keyple.calypso.command.csm.parser

abstract AbstractCsmCommandBuilder {
  #CsmRevision defaultRevision = CsmRevision.C1
  +AbstractCsmCommandBuilder(CalypsoSmCommands reference, ApduRequest request)
}

enum CsmRevision {
  C1
  S1D
}

'CsmRevision "+1" -left- "1..*" AbstractCsmCommandBuilder
CsmRevision "+1" -right- "1..*" AbstractCsmCommandBuilder

PsoComputeSignatureCmdBuild --|> AbstractCsmCommandBuilder : extends
PsoVerifySignatureCmdBuild --|> AbstractCsmCommandBuilder : extends
SelectDiversifierCmdBuild --|> AbstractCsmCommandBuilder : extends
'GetChallengeCmdBuild --|> AbstractCsmCommandBuilder : extends
DigestInitCmdBuild --|> AbstractCsmCommandBuilder : extends
DigestUpdateCmdBuild --|> AbstractCsmCommandBuilder : extends
'DigestUpdateMultipleCmdBuild --|> AbstractCsmCommandBuilder : extends
'DigestCloseCmdBuild --|> AbstractCsmCommandBuilder : extends
'DigestAuthenticateCmdBuild --|> AbstractCsmCommandBuilder : extends

org.eclipse.keyple.calypso.command.csm.builder -down[hidden]- AbstractCsmCommandBuilder
}
@enduml

