' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' All rights reserved. This program and the accompanying materials are made available under the
' terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
' available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html

@startuml
hide footbox

actor CPO as P
participant "Calypso processing\nterminal with local\nPO & CSM readers" as T
actor CSM as S

P<-T: **[1]** SelectApplication(AID)
P-->>T: PO serial
group 'x' PO commands
P<-T: **[2]** Free Read/Write commands outside session
P-->>T: commands' responses
...
P<-T: **[1 + x]** Free Read/Write commands outside session
P-->>T: commands' responses
end
T->S: **[1]** SelectDiversifier(PO serial)
T<<--S: ack
T->S: **[2]** GetChallenge
T<<--S: CSM challenge
P<-T: **[2 + x]** OpenSession(key index, CSM challenge, record to read)
P-->>T: PO challenge, key reference, read data
T->S: **[3]** DigestInit(OpenSession data)
T<<--S:ack
group 'y' PO commands
P<-T: **[3 + x]** Read/Write commands inside session
P-->>T: commands' responses
...
P<-T: **[2 + x + y]** Read/Write commands inside session
P-->>T: commands' responses
end
group '2 * y' session MAC updates with PO commands
T->S: **[4]** DigestUpdate(PO command)
T<<--S: ack
T->S: **[5]** DigestUpdate(PO response)
T<<--S: ack
...
T->S: **[3 + (2*y-1)]** DigestUpdate(PO command)
T<<--S: ack
T->S: **[3 + 2*y]** DigestUpdate(PO response)
T<<--S: ack
end
T->S: **[4 + 2*y]** DigestClose
T<<--S: CSM certificate
P<-T: **[3 + x + y]** CloseSession(CSM certificate)
P-->>T: PO certificate
P<-T: **[4 + x + y]** Ratification command
P-->>T: ack
T->S: **[5 + 2*y]** ExternalAuthenticate(PO certificate)
T<<--S: authentication status
@enduml
