' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' All rights reserved. This program and the accompanying materials are made available under the
' terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
' available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html

@startuml
start
:PO status: not selected\nMessages: PO [0] - CSM [0] }
:**Select PO** (Data read outside session)
(step 1);
:PO status: selected\nMessages: PO [1] - CSM [0] }
if (additional PO commands\ninside the session with non anticipated responses?) then (no)
  :**Process Opening & Closing**
  (step 2);
  if (PO logical channel closed?) then (no)
    :PO status: selected\nMessages: PO [3] - CSM [3] }
  else (yes)
    :PO status: not selected\nMessages: PO [3] - CSM [3] }
  endif
else (yes)
  :**Process Opening**
  (step 2);
  :PO status: session open\nMessages: PO [2] - CSM [2] }
    if (anticipated responses\nfor additional PO commands?) then (yes)
      :**Process Closing**
	  (step 3);
	  if (PO logical channel closed?) then (no)
        :PO status: selected\nMessages: PO [3] - CSM [4] }
      else (yes)
        :PO status: not selected\nMessages: PO [3] - CSM [4] }
      endif
    else (no)
      :**Process Proceed**
	  (step 3);
      :PO status: session open\nMessages: PO [3] - CSM [4] }
	  :**Process Closing**
	  (step 4);

	  if (PO logical channel closed?) then (no)
        :PO status: selected\nMessages: PO [4] - CSM [5] }
      else (yes)
        :PO status: not selected\nMessages: PO [4] - CSM [5] }
      endif
	endif
endif
'}
stop
@enduml