' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' All rights reserved. This program and the accompanying materials are made available under the
' terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
' available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html

@startuml
hide footbox

actor CPO as PO
participant "PO local\nProxyReader" as POR
participant "Ticketing\napplication" as TA
participant "Keyple\nCalypso API" as KC
participant "CSM local\nProxyReader" as SMR
actor CSM as SM

== PO Identification ==

TA->KC: transmit(SeRequest(AID,\nList<PoRequestOutSession>))
POR<[#0000FF]-KC: PO 1: SeRequest(AID, List<ApduRequest>)
PO<-POR: SelectApplication
PO-->>POR: PO serial
group 'x' PO commands outside session
PO<-POR: ApduRequest
PO-->>POR: ApduResponse
end
POR--[#0000FF]>KC: SeResponse(FCI, List<ApduResponse>)
TA<--KC: SeResponse(PO_FCI, List<PoResponse>))

== PO Secure Session ==

TA->KC: **processIdentification**(PO_FCI)
KC-[#00FF00]>SMR: CSM 1: SeRequest(noAID,\nList<ApduRequest>)
SMR->SM: SelectDiversifier
SMR<<--SM: ack
SMR->SM: GetChallenge
SMR<<--SM: CSM challenge
KC<<[#00FF00]--SMR: SeResponse(FCI, List<ApduResponse>)
TA<<--KC: SessionStatus_Identified

TA->KC: **processOpening**(OpenSessionRequest,\nList<PoRequestInSession>)
POR<[#0000FF]-KC: PO 2: SeRequest(AID, List<ApduRequest>)
PO<-POR: OpenSession
PO-->>POR: PO challenge
group 'y' PO commands inside session
PO<-POR: ApduRequest
PO-->>POR: ApduResponse
end
POR--[#0000FF]>KC: SeResponse(FCI, List<ApduResponse>)
KC-[#00FF00]>SMR: CSM 2: SeRequest(noAID,\nList<ApduRequest>)
SMR->SM: DigestInit
SMR<<--SM:ack
group '2 * y' session MAC updates
SMR->SM: DigestUpdate
SMR<<--SM: ack
SMR->SM: DigestUpdate
SMR<<--SM: ack
end
KC<<[#00FF00]--SMR: SeResponse(FCI,\nList<ApduResponse>)
TA<<--KC: SessionState_Open, List<PoResponse>

TA->KC: **processClosing**(List<PoRequestInSession>,\nList<AnticipatedPoResponse>,\nPoRatificationCommand)
KC-[#00FF00]>SMR: CSM 3: SeRequest(noAID,\nList<ApduRequest>)
group '2 * z' session MAC updates
SMR->SM: DigestUpdate
SMR<<--SM: ack
SMR->SM: DigestUpdate
SMR<<--SM: ack
end
SMR->SM: DigestClose
SMR<<--SM: CSM certificate
KC<<[#00FF00]--SMR: CSM certificate
POR<[#0000FF]-KC: PO 3: SeRequest(AID,\nList<PoRequest>)
group 'z' PO commands inside session
PO<-POR: ApduRequest
PO-->>POR: ApduResponse
end
PO<-POR: CloseSession
PO-->>POR: PO certificate
PO<-POR: Ratification
PO-->>POR: ack
POR--[#0000FF]>KC: SeResponse(FCI, List<ApduResponse>)
KC-[#00FF00]>SMR: CSM 4: SeRequest(noAID, List<ApduRequest>)
SMR->SM: ExternalAuthenticate
SMR<<--SM: authentication status
KC<<[#00FF00]--SMR: Authentification status
TA<<--KC: SessionState_Closed, List<PoResponse>
@enduml
