////
 Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/

 All rights reserved. This program and the accompanying materials are made available under the
 terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
 available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html
////
==  Commands' Sets - (Low layer processing)

=== Organization

PO & CSM APDU request builder classes have to extend ApduCommandBuilder:

* the daughter sub-classes have to provide the dedicated constructor to build the specific APDU,
* the mother class defines the ApduRequest attribute.

PO & CMS APDU response parser classes have to extend ApduResponseParser:

* the daughter sub-classes have to provide the dedicated getters to access to the specific fields of the APDU response,
* the mother class defines the ApduResponse attribute, and the generic abstract constructor.

image::./img/uml-classDiagram-CalypsoCommand-CalypsoTable.svg[Class Diagram - Calypso Commands Tables]
////
[uml,file="../../images/build/uml-classDiagram-CalypsoCommand-CalypsoTable.svg"]
--
!include ../iuml/KeypleClassDiagram_CalypsoCommand_Base.iuml
--
////
The classes and interfaces necessary to manage APDU Command Builders & Response Parser are contained in the ‘org.eclipse.keyple.command’ package.

