////
 Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/

 All rights reserved. This program and the accompanying materials are made available under the
 terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
 available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html
////
== Secure Transaction - (High layer processing)

The high level Calypso transaction module is defined on top of the PO & CSM commands’ API, its classes and interface will be contained in the package ‘org.eclipse.keyple.calypso.transaction’,

The aim of this transaction module is to automate security operations linked to a session or a transaction. Through this layer of API, an application doesn’t require to manage directly CSM operations (like proposed by lots of contactless readers which embed CSM slots.

=== PO & CSM flows during a Calypso Secure Session

A plain secure session with a Calypso PO involves the management of two SE readers in order to communicate in parallel with both a Calypso PO and a CSM.

A ticketing transaction often requires the exchange of a dozen of PO commands.

* The number of APDU command send to the PO reader is at least four plus the number of PO commands exchanged outside the session, and plus the number of PO commands exchanged inside the session.
* The number of APDU command send to the CSM reader is at least five plus twice the number of PO commands exchanged inside the session.

image::./img/uml-sequenceDiagram-CalypsoTransaction-ClassicPoSecureSession.svg[Sequence Diagram - Calypso Sesure Session]
////
[uml,file="../../images/build/uml-sequenceDiagram-CalypsoTransaction-ClassicPoSecureSession.svg"]
--
!include ../iuml/KeypleSequenceDiagram_CalypsoTransaction_ClassicPoSecureSession.iuml
--
////

=== Class: PoSecureSession

A non-encrypted secure session with a Calypso PO requires the management of two ProxyReader in order to communicate with both a Calypso PO and a CSM.

* Method: **PoSecureSession** (ProxyReader poReader, ProxyReader csmSessionReader, byte defaultKeyIndex)
** Logical channels with PO & CSM could already be established or not.
** defaultKeyIndex optionnaly indicates the default CSM key for a PO Secure Session ([red]#this parameter  may evolve to allow wider CSM settings#).

* Method: void **processIdentification** (ApduResponse poFciData)
** The PO must have previously been selected, so a logical channel with the PO application must be active. No additional communication is made with the PO during this operation. The PO serial & revision are identified from FCI data.
** On the CSM session reader, in case not logical channel is active, a channel is open; and a Select Diversifier (with the PO serial) & a Get Challenge are automatically operated. 

* Method: SeResponse **processOpening** (AbstractOpenSessionCmdBuild openCommand, List<PoSendableInSession> poCommandsInsideSession)
** On the PO reader, generate a SeRequest with the current selected AID, with keepChannelOpen set at true, and apduRequests defined with the openCommand and optionally some poCommandsInsideSession.
** The session PO keyset reference is identified from the PO Open Session response.
** On the CSM session reader, a Digest Init & potentially several Digest Update Multiple (to update the session MAC according to the PO commands sent in session) are automatically operated.
** Returns the corresponding PO SeResponse (for openCommand and poCommandsInsideSession).

* Method: SeResponse **processProceeding** (List<PoSendableInSession> poCommandsInsideSession)
** On the PO reader, generates a SeRequest for the current selected AID, with keepChannelOpen set at true, and apduRequests defined with the poCommandsInsideSession.
** On the CSM session reader, automatically operates some corresponding Digest Update Multiple.
** Returns the corresponding PO SeResponse (for poCommands_InsideSession).

* Method: SeResponse **processClosing** (List<PoSendableInSession> poCommandsInsideSession, List<ApduResponse> poAnticipatedResponseInsideSession, AbstractPoCommandBuilder ratificationCommand, boolean closeSeChannel)
** On the CSM session reader, if present potentially operates automatically several Digest Update Multiple for PO commands with **anticipated responses**, and the Digest Close to get the CSM certificate. The terminal signature is identified.
** Next on the PO reader, generates a SeRequest with the current selected AID, with keepChannelOpen set at the reverse value of closeSeChannel, and apduRequests including the optional poCommandsInsideSession, a Close Session command, & optionally a ratificationCommand.
** The PO responses of the poCommandsInsideSession are compared with the poAnticipatedResponseInsideSession. The PO signature is identified from the PO Close Session response.
** Finally, on the CSM session reader, Digest Authenticate is automatically operated in order to authenticate the PO.
** Returns the corresponding PO SeResponse.

* Method: SeResponse **processOpeningClosing** (AbstractOpenSessionCmdBuild openCommand, List<PoSendableInSession> poCommandsInsideSession, AbstractPoCommandBuilder ratificationCommand, boolean closeSeChannel)
** Firstly, on the PO reader, generates a SeRequest with the currently selected AID, with keepChannelOpen set true, and apduRequests defined with the openCommand, optionally some poCommandsInsideSession.
** The session PO keyset reference is identified from the PO Open Session response.
** On the CSM session reader, a Digest Init & potentially several Digest Update Multiple (to update the session MAC according to the PO commands sent in session), and a Digest Close are automatically operated. The terminal signature is identified.
** Next on the PO reader, another SeRequest is transmitted for the currently selected AID, with keepChannelOpen set at the reverse value of closeSeChannel, and a Close Session command, & optionally a ratificationCommand.
** Finally, on the CSM session reader, Digest Authenticate is automatically operated in order to authenticate the PO.
** Returns the corresponding PO SeResponse (for openCommand, poCommandsInsideSession, and the Close Session).

* Method: SeResponse **processCsmCommands** (List<CsmSendableInSession> csmSendableInSessions)
** This method allows to request a CSM computation other than the session management during a PO secure session: a signature or encryption specific operation on data.

* Method: boolean **isSuccessful** ()
** To check the result of a closed secure session, returns true if the CSM Digest Authenticate is successful.

[red]#Possible improvement: addition of a csmSendableInSessions parameter for the methods processOpening & processProceeding#

=== Secure transaction modes

Without CSM request for a specific computation (without usage of processCsmCommands), the PoSecureSession API allows to operate a Calypso Secure Session in 2 to 4 steps:

* **2 steps** transaction: in case the session could be directly open and closed (useful for a simple PO authentication transaction with a remote CSM); using this mode, only **3 messages are required with the PO ProxyReader and with the CSM ProxyReader**,
* **3 steps** transaction:  after the processing of the Open Session response, some additional PO commands with "anticipated" results are requested at the close; this mode requires still the exchanges of **3 messages with the PO ProxyReader**, but **4 messages with the CSM ProxyReader**.
* **4 steps** transaction: in case additional PO commands without anticipated results; **4 messages with the PO ProxyReader** are necessary, and **5 messages with the CSM ProxyReader**.

image::./img/uml-activityDiagram-CalypsoTransaction-SessionModes.svg[Activity Diagram - PoSecureTransaction Modes]
////
[uml,file="../../images/build/uml-activityDiagram-CalypsoTransaction-SessionModes.svg"]
--
!include ../iuml/KeypleActivityDiagram_CalypsoTransaction_SessionModes.iuml
--
////

=== ProxyReader flows for a 3 steps secure transaction

image::./img/uml-sequenceDiagram-CalypsoTransaction-3stepsecureSession.svg[Sequence Diagram - 3 steps PoSecureTransaction]
////
[uml,file="../../images/build/uml-sequenceDiagram-CalypsoTransaction-3stepsecureSession.svg"]
--
!include ../iuml/KeypleSequenceDiagram_CalypsoTransaction_3stepsSecureSession.iuml
--
////



