////
 Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/

 All rights reserved. This program and the accompanying materials are made available under the
 terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
 available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html
////
== Secure Transaction - (High layer processing)

The high level Calypso transaction module is defined on top of the PO & CSM commands’ API, its classes and interface will be contained in the package ‘org.eclipse.keyple.calypso.transaction’,

The aim of this transaction module is to automate security operations linked to a session or a transaction. Through this layer of API, an application doesn’t require to manage directly CSM operations (like proposed by lots of contactless readers which embed CSM slots.

=== PO & CSM flows during a Calypso Secure Session

A plain secure session with a Calypso PO involves the management of two SE readers in order to communicate in parallel with both a Calypso PO and a CSM.

A ticketing transaction often requires the exchange of a dozen of PO commands.

* The number of APDU command send to the PO reader is at least four plus the number of PO commands exchanged outside the session, and plus the number of PO commands exchanged inside the session.
* The number of APDU command send to the CSM reader is at least five plus twice the number of PO commands exchanged inside the session.

image::./img/uml-sequenceDiagram-CalypsoTransaction-ClassicPoSecureSession.svg[Sequence Diagram - Calypso Sesure Session]
////
[uml,file="../../images/build/uml-sequenceDiagram-CalypsoTransaction-ClassicPoSecureSession.svg"]
--
!include ../iuml/KeypleSequenceDiagram_CalypsoTransaction_ClassicPoSecureSession.iuml
--
////

=== PO & CSM messages grouping

The PoSecureSession API allows to operate a **Calypso Secure Session with only 3 PO messages and 3 CSM messages**:

* PO identification:
** The PO must be selected beforehand: the first PO message is corresponding to this selection.
** The selection of the PO application could be included in a SeRequestSet based on several SeRequest trying to match the different PO supported by the terminal.
** The PO selection SeRequest could contain additional PO commands to operate before (outside) the secure session 

* PO session:
** The logical channels with the selected PO & the CSM should be maintained during all the session. During the session, PO & CSM SeRequestSet must be defined on a single SeRequest. 
** PO messages:
*** The second PO message is the opening of the secure session: this request could include some PO commands.
*** The third PO message is the closing of the session: this request could include PO commands only if the data of the corresponding responses is predertermined.
*** If necessary, some additinal PO messages could be operated (PO commends defined as sendable in a session).
** CSM messages 
*** All the CSM commands managing the PO secured session certificate computation are automatically generated by the API.
*** A first CSM message allows to recover the CSM challenge.
*** Durign the secure session, all CSM doing the session MAC computation could grouped (CSM Digest commands) and transmited in a second CSM message.
*** A third CSM message is necessary to verify the PO certificate.
*** If necessary,  somme additional CSM messages could be operated (useful for PSO or data cipher operation).

////
image::./img/uml-activityDiagram-CalypsoTransaction-SessionModes.svg[Activity Diagram - PoSecureTransaction Modes]
////
////
[uml,file="../../images/build/uml-activityDiagram-CalypsoTransaction-SessionModes.svg"]
--
!include ../iuml/KeypleActivityDiagram_CalypsoTransaction_SessionModes.iuml
--
////

=== Class: PoSecureSession

A non-encrypted secure session with a Calypso PO requires the management of two ProxyReader in order to communicate with both a Calypso PO and a CSM.

* Method: **PoSecureSession** (ProxyReader poReader, ProxyReader csmSessionReader, byte defaultKeyIndex)
** Logical channels with PO & CSM could already be established or not.
** defaultKeyIndex optionnaly indicates the default CSM key for a PO Secure Session ([red]#this parameter  may evolve to allow wider CSM settings#).

* Method: SeResponse **processOpening** (ApduResponse poFciData, AbstractOpenSessionCmdBuild openCommand, List<PoSendableInSession> poCommandsInsideSession)
** The PO must have been previously selected, so a logical channel with the PO application must be already active.
** The PO serial & revision are identified from FCI data.
** A first request is sent to the CSM session reader.
*** In case not logical channel is active with the CSM, a channel is open.
*** Then a Select Diversifier (with the PO serial) & a Get Challenge are automatically operated. 
** The CSM challenge is recovered:
** Next the PO reader is requested:
*** for the current selected PO AID, with keepChannelOpen set at true,
*** and some PO Apdu Requests including at least an Open Session command (defined with the CSM challenge), and optionally some PO command to operate inside the session.
** The session PO keyset reference is identified from the PO Open Session response, the PO challenge is recovered too.
** According to the PO responses of Open Session and the PO commands sent inside the session, a "cache" of CSM commands is filled with the corresponding Digest Init & Digest Update commands.
** Returns the corresponding PO SeResponse (for openCommand and poCommandsInsideSession).

* Method: SeResponse **processPoCommands** (List<PoSendableInSession> poCommands)
** On the PO reader, generates a SeRequest for the current selected AID, with keepChannelOpen set at true, and ApduRequests with the PO commands.
** In case the secure session is active, the "cache" of CSM commands is completed with the corresponding Digest Update commands.
** Returns the corresponding PO SeResponse.

* Method: SeResponse **processCsmCommands** (List<CsmSendableInSession> csmCommands)
** The CSM commands to operate are pushed in the current CSM commands cache.
** On the CSM reader, transmission of a SeRequest for the current selected AID, with keepChannelOpen set at true, and ApduRequests based on all the CSM commands of the cache. The cache emptied.
** Returns the corresponding CSM SeResponse.

* Method: SeResponse **processClosing** (List<PoSendableInSession> poCommandsInsideSession, List<ApduResponse> poAnticipatedResponseInsideSession, PoSendableInSession ratificationCommand, boolean closeSeChannel)
** The CSM cache is completed with the Digest Update commands related to the new PO commands to send and their anticipated responses. A Digest Close command is also added to the CSM cache.
** On the CSM session reader, a SeRequest is transmitted with CSM commands of the cache. The CSM cache is emptied.
** The CSM certificate is recovered from the Digest Close response. The terminal signature is identified.
** Next on the PO reader, a SeRequest is transmitted for the current selected AID, with keepChannelOpen set at the reverse value of closeSeChannel, and apduRequests including the new PO commands to send in the session, a Close Session command (defined with the CSM certificate), and optionally a ratificationCommand.
** The PO responses of the poCommandsInsideSession are compared with the poAnticipatedResponseInsideSession. The PO signature is identified from the PO Close Session response.
** The PO certificate is recovered from the Close Session response. The card signature is identified.
** Finally, on the CSM session reader, a Digest Authenticate is automatically operated in order to authenticate the PO.
** Returns the corresponding PO SeResponse.

* Method: boolean **isSuccessful** ()
** To check the result of a closed secure session, returns true if the CSM Digest Authenticate is successful.

=== ProxyReader flows for a secure transaction

image::./img/uml-sequenceDiagram-CalypsoTransaction-3stepsecureSession.svg[Sequence Diagram - 3 steps PoSecureTransaction]
////
[uml,file="../../images/build/uml-sequenceDiagram-CalypsoTransaction-3stepsecureSession.svg"]
--
!include ../iuml/KeypleSequenceDiagram_CalypsoTransaction_3stepsSecureSession.iuml
--
////



