////
 Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/

 All rights reserved. This program and the accompanying materials are made available under the
 terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
 available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html
////
=== Calypso Secure Module command's set

All the related elements are located in the package 'org.eclipse.keyple.calypso.command.csm'.

image::./img/uml-classDiagram-CalypsoCommand-CsmCommands.svg[Class Diagram - Calypso CSM Commands Table]
////
[uml,file="../../images/build/uml-classDiagram-CalypsoCommand-CsmCommands.svg"]
--
!include ../iuml/KeypleClassDiagram_CalypsoCommand_Csm.iuml
--
////

* Builders of CSM command are included in the sub-package 'org.eclipse.keyple.calypso.command.csm.builder', related classes *extend AsbstractCsmCommandBuilder*.
* Parsers of CSM response are located in the sub-package 'org.eclipse.keyple.calypso.command.csm.parser', related classes *extend AbstractApduResponseParser*.

==== CSM commands table

==== Enumeration: CalypsoSmCommands

This enumeration registers all the CSM commands managed by the library, the enumeration implements the CommandsTable Interface.
It provides the generic getters to retrieve: the name of the command, the built ApduRequest and, the corresponding ApduResponseParser class.

* Structured literals:

[cols=",,,,,",options="header",]
|=======================================================================
| |*‘name’* |*‘ins’* |*‘cmdBuilderClass’* |*‘respParserClass’*
|CSM_SELECT_DIVERSIFIER |“Select Diversifier” |0x14 |SelectDiversifierCmdBuild |SelectDiversifierRespPars
|CSM_GET_CHALLENGE |“Get Challenge” |0x84 |CsmGetChallengeCmdBuild |CsmGetChallengeRespPars
|CSM_DIGEST_INIT |“Digest Init” |0x8A |DigestInitCmdBuild |DigestInitRespPars
|CSM_DIGEST_UPDATE |“Digest Update” |0x8C |DigestUpdateCmdBuild |DigestUpdateRespPars
|CSM_DIGEST_UPDATE_MULTIPLE |“Digest Update Multiple” |0x8C |DigestUpdateCmdBuild |DigestUpdateRespPars
|CSM_DIGEST_CLOSE |“Digest Close” |0x8E |DigestCloseCmdBuild |DigestCloseRespPars
|CSM_DIGEST_AUTHENTICATE |“Digest Authenticate” |0x82 |DigestAuthenticateCmdBuild |DigestAuthenticateRespPars
|=======================================================================

==== Enumeration: CsmRevision

This enumeration registers the different mode of CSM. Currently the specific CSM feature identified is the support of ISO 7816-4 commands’ (C1 & S1E SAM with commands in CLA 80h), or proprietary commands (S1D SAM with commands in CLA 94h).

* Literals:

[cols="",options="header",]
|====
|C1
|S1D
|====

==== abstract Class: CsmCommandBuilder

This *abstract* class *extends* ApduCommandBuilder, it has to be *extended by all CSM command builder classes*, it manages the current default revision for PO commands.

* *static* Attribute: CsmRevision defaultRevision
** the current default revision for CsmCommandBuilder.
* *abstract* Method: CsmCommandBuilder(CalypsoCommands reference, ApduRequest request)
** the generic abstract constructor to build an CSM request with a Calypso command’s reference and a byte array.

==== CSM commands' builders

===== Class: SelectDiversifierCmdBuild

This class *extends* CsmCommandBuilder, it provides the dedicated constructor to build the CSM Get Challenge APDU command.

* Method: SelectDiversifierCmdBuild (CsmRevision[0..1] revision, ByteArray diversifier) *throw* InconsistentCommandException
** The CalypsoCommands reference is defined with the value ‘CSM_SELECT_DIVERSIFIER’.
** If the *optional* revision parameter is missing, use the current CsmCommandBuilder.defaultRevision. In revision ‘S1D’, the class byte is set at 94h (otherwise at 80h).
* Method: SelectDiversifierCmdBuild (ApduRequest request) *throw* InconsistentCommandException
** Bytes low level constructor: throw an exception if the request’s instruction code isn’t the one defined for ‘CSM_SELECT_DIVERSIFIER’ CalypsoCommands’ reference, otherwise call the super constructor.

===== Class: CsmGetChallengeCmdBuild

This class *extends* CsmCommandBuilder, it provides the dedicated constructor to build the CSM Get Challenge APDU command.

* Method: CsmGetChallengeCmdBuild (CsmRevision[0..1] revision, Byte expectedResponseLength) *throw* InconsistentCommandException
** The CalypsoCommands reference is defined with the value ‘CSM_GET_CHALLENGE’.
** If the *optional* revision parameter is missing, use the current CsmCommandBuilder.defaultRevision. In revision ‘S1D’, the class byte is set at 94h (otherwise at **0**0h).
* Method: CsmGetChallengeCmdBuild (ApduRequest request) *throw* InconsistentCommandException
** Bytes low level constructor: throw an exception if the request’s instruction code isn’t the one defined for ‘CSM_GET_CHALLENGE’ CalypsoCommands’ reference, otherwise call the super constructor.

===== Class: DigestInitCmdBuild

This class *extends* CsmCommandBuilder, it provides the dedicated constructor to build the Digest Init APDU command.

* Method: DigestInitCmdBuild (CsmRevision[0..1] revision, Boolean verificationMode, Boolean rev3_2Mode, Byte[0..1] workKeyRecordNumber, Byte[0..1] workKeyKIF, Byte[0..1] workKeyKVC, ByteArray digestData) *throw* InconsistentCommandException
** The CalypsoCommands reference is defined with the value ‘CSM_DIGEST_INIT’.
** If the *optional* revision parameter is missing, use the current CsmCommandBuilder.defaultRevision. In revision ‘S1D’, the class byte is set at 94h (otherwise at 80h).
** If workKeyRecordNumber is missing, workKeyKIF & workKeyKVC have to be present.
* Method: DigestInitCmdBuild (ApduRequest request) *throw* InconsistentCommandException
** Bytes low level constructor: throw an exception if the request’s instruction code isn’t the one defined for ‘CSM_DIGEST_INIT’ CalypsoCommands’ reference, otherwise call the super constructor.

===== Class: DigestUpdateCmdBuild

This class *extends* CsmCommandBuilder, it provides the dedicated constructor to build the Digest Update APDU command.

* Method: DigestUpdateCmdBuild (CSMRevision[0..1] revision, Boolean encryptedSession, ByteArray[0..1] digestData) *throw* InconsistentCommandException
** The CalypsoCommands reference is defined with the value ‘CSM_DIGEST_UPDATE’.
** If the *optional* revision parameter is missing, use the current CsmCommandBuilder.defaultRevision. In revision ‘S1D’, the class byte is set at 94h (otherwise at 80h).
** If digestData missing, ask to abort the session.
* Method: DigestUpdateCmdBuild (ApduRequest request) *throw* InconsistentCommandException
** Bytes low level constructor: throw an exception if the request’s instruction code isn’t the one defined for ‘CSM_DIGEST_UPDATE’ CalypsoCommands’ reference, otherwise call the super constructor.

===== Class: DigestUpdateMultipleCmdBuild

This class *extends* CsmCommandBuilder, it provides the dedicated constructor to build the Digest Update APDU command.

* Method: DigestUpdateMultipleCmdBuild (CsmRevision[0..1] revision, ByteArray[0..1] digestData) *throw* InconsistentCommandException
** The CalypsoCommands reference is defined with the value ‘CSM_DIGEST_UPDATE_MULTIPLE’.
** If the *optional* revision parameter is missing, use the current CsmCommandBuilder.defaultRevision. In revision ‘S1D’, the class byte is set at 94h (otherwise at 80h).
** If digestData missing, ask to abort the session.
* Method: DigestUpdateMultipleCmdBuild (ApduRequest request) *throw* InconsistentCommandException
** Bytes low level constructor: throw an exception if the request’s instruction code isn’t the one defined for ‘CSM_DIGEST_UPDATE_MULTIPLE’ CalypsoCommands’ reference, otherwise call the super constructor.

===== Class: DigestCloseCmdBuild

This class *extends* CsmCommandBuilder, it provides the dedicated constructor to build the Digest Close APDU command.

* Method: DigestCloseCmdBuild (CsmRevision[0..1] revision, Byte expectedResponseLength) *throw* InconsistentCommandException
** The CalypsoCommands reference is defined with the value ‘CSM_DIGEST_CLOSE’.
** If the *optional* revision parameter is missing, use the current CsmCommandBuilder.defaultRevision. In revision ‘S1D’, the class byte is set at 94h (otherwise at 80h).
* Method: DigestCloseCmdBuild (ApduRequest request) *throw* InconsistentCommandException
** Bytes low level constructor: throw an exception if the request’s instruction code isn’t the one defined for ‘CSM_DIGEST_ CLOSE’ CalypsoCommands’ reference, otherwise call the super constructor.

===== Class: DigestAuthenticateCmdBuild

This class *extends* CsmCommandBuilder, it provides the dedicated constructor to build the Digest Authenticate APDU command.

* Method: DigestAuthenticateCmdBuild (CsmRevision[0..1] revision, ByteArray signature) *throw* InconsistentCommandException
** The CalypsoCommands reference is defined with the value ‘CSM_DIGEST_AUTHENTICATE’.
** If the *optional* revision parameter is missing, use the current CsmCommandBuilder.defaultRevision. In revision ‘S1D’, the class byte is set at 94h (otherwise at 80h).
* Method: DigestAuthenticateCmdBuild (ApduRequest request)
** Bytes low level constructor: throw an exception if the request’s instruction code isn’t the one defined for ‘CSM_DIGEST_AUTHENTICATE’ CalypsoCommands’ reference, otherwise call the super constructor.

==== CSM responses' parsers

All these classes *extend ApduResponseParser* and are located in the
package 'org.eclipse.keyple.calypso.command.csm.parser'.

===== Class: SelectDiversifierRespPars

(No additional getter)

* Method: SelectDiversifierRespPars (ApduResponse responseToParse)

===== Class: CsmGetChallengeRespPars

* Method: CsmGetChallengeRespPars (ApduResponse responseToParse)
* Method: ByteArray getChallenge()

===== Class: DigestInitRespPars

(No additional getter)

* Method: DigestInitRespPars (ApduResponse responseToParse)

===== Class: DigestUpdateRespPars

* Method: DigestUpdateRespPars (ApduResponse responseToParse)
* Method: ByteArray getProcessedData()

===== Class: DigestUpdateMultipleRespPars

(No additional getter)

* Method: DigestUpdateMultipleRespPars (ApduResponse responseToParse)

===== Class: DigestCloseRespPars

* Method: DigestCloseRespPars (ApduResponse responseToParse)
* Method: ByteArray getSignature()

===== Class: DigestAuthenticateRespPars

(No additional getter)

* Method: DigestAuthenticateRespPars (ApduResponse responseToParse)


