////
 Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/

 All rights reserved. This program and the accompanying materials are made available under the
 terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
 available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html
////
=== Calypso Portable Object command's set

The Calypso PO commands are defined in the package 'org.eclipse.keyple.calypso.command.po'.

image::./img/uml-classDiagram-CalypsoCommand-PoCommands.svg[Class Diagram - Calypso PO Commands Table]
////
[uml,file="../../images/build/uml-classDiagram-CalypsoCommand-PoCommands.svg"]
--
!include ../iuml/KeypleClassDiagram_CalypsoCommand_Po.iuml
--
////

* Builders of PO command are included in the sub-package 'org.eclipse.keyple.calypso.command.po.builder', related classes extend AsbstractPoCommandBuilder.
* Parsers of PO response are located in the sub-package 'org.eclipse.keyple.calypso.command.po.parser', related classes extend AbstractApduResponseParser.

==== Calypso PO commands table

==== Enumeration: CalypsoPoCommands

This enumeration registers all the Calypso PO commands managed by the library, the enumeration implements the CommandsTable Interface.
It provides the generic getters to retrieve: the name of the command, the built ApduRequest and, the corresponding ApduResponseParser class.

* Structured literals:

[cols=",,,,,",options="header",]
|=======================================================================
| |*‘name’* |*‘ins’* |*‘cmdBuilderClass’* |*‘respParserClass’*
|PO_GET_DATA_FCI |“Get Data ‘FCI’” |0xCA |GetDataFciCmdBuild |PoFciRespPars
|PO_OPEN_SESSION |“Open Secure Session” |0x8A |OpenSessionCmdBuild |OpenSessionRespPars
|PO_CLOSESESSION |“Close Secure Session” |0x8E |CloseSessionCmdBuild |CloseSessionRespPars
|PO_READ_RECORDS |“Read Records” |0xB2 |ReadRecordsCmdBuild |ReadRecordsRespPars
|PO_UPDATE_RECORD |“Update Record” |0xDC |UpdateRecordCmdBuild |UpdateRecordRespPars
|PO_GET_CHALLENGE |“Get Challenge” |0x84 |PoGetChallengeCmdBuild |PoGetChallengeRespPars
|=======================================================================

*An application could manage additional Commands by providing another implementation of the CommandsTable Interface.*

==== Enumeration: PoRevision

This enumeration registers the different Calypso revisions supported by PO, it is used to build a PO Commands in a mode specific to a PO revision.

* Structured literals:

[cols=",",options="header",]
|============================
| |*‘name’*
|REV2_4 |Calypso Revision 2.4
|REV3_1 |Calypso Revision 3.1
|REV3_2 |Calypso Revision 3.2
|============================

==== abstract Class: PoCommandBuilder

This *abstract* class *extends* ApduCommandBuilder, it has to be *extended by all PO command builder classes*, it manages the current default revision for PO commands.

* *static* Attribute: PoRevision defaultRevision
** the current default revision for PoCommandBuilder.
* *abstract* Method: PoCommandBuilder(CalypsoCommands reference,
ApduRequest request)
** the generic abstract constructor to build an PO request with a
Calypso command’s reference and a byte array.

==== Calypso PO commands' builders 

===== Class: GetDataFciCmdBuild

This class *extends* PoCommandBuilder and *implements* SendableInSession, it provides the dedicated constructor to build the Get Data for ‘FCI’ APDU command.

* Method: GetDataFCICmdBuild (PoRevision[0..1] revision)
** The CalypsoCommands reference is defined with the value ‘PO_GET_DATA_FCI’.
** If the *optional* revision parameter is missing, use the current PoCommandBuilder.defaultRevision. In revision 1 & 2, the class byte is set at 94h (otherwise at 00h).
* Method: GetDataFCICmdBuild (ApduRequest request) *throw* InconsistentCommandException
** The CalypsoCommands reference is defined with the value ‘PO_GET_DATA_FCI’.
** Bytes low level constructor: throw an exception if the request’s instruction code isn’t the one defined for ‘PO_GET_DATA_FCI’ CalypsoCommands’ reference, otherwise call the super constructor.

[cols="",]
|=======================================================================
a|
Remark:

* In Java or C++, *several constructors* could be defined to manage the
*optional parameters*.

* About the different modes of the Calypso PO Get Data command:
** Through a CommandsTable, an ApduCommandBuilder could be linked to only one ApduResponseParser.
** Depending on P1/P2 parameters the Calypso PO GetData command could returned different kind of structured response. It seems preferable to define a specific ApduResponseParser for each mode of the Get Data command. Then it makes sense to define a specific ApduCommandBuilder for each mode of the Get Data command.

To study,

* Maybe an abstract ‘GetDataCmdBuild’ class could be defined to support all the modes of the Get Data command, and then GetDataFCICmdBuild could extend it. In this case the constructor of GetDataCmdBuild may contain a parameter specifying the mode of the command, all modes being defined in an enumeration.

|=======================================================================

===== Class: PoGetChallengeCmdBuild

This class *extends* PoCommandBuilder *implements* SendableInSession, it provides the dedicated constructor to build the PO Get Challenge.

* Method: PoGetChallengeCmdBuild (PoRevision[0..1] revision)
** The CalypsoCommands reference is defined with the value ‘PO_GET_CHALLENGE’.
** If the *optional* revision parameter is missing, use the current PoCommandBuilder.defaultRevision. In revision 1 & 2, the class byte is set at 94h (otherwise at 00h).
* Method: PoGetChallengeCmdBuild (ApduRequest request) *throw* InconsistentCommandException
** Bytes low level constructor: throw an exception if the request’s instruction code isn’t the one defined for ‘PO_GET_CHALLENGE’ CalypsoCommands’ reference, otherwise call the super constructor.

===== Class: OpenSessionCmdBuild

This class *extends* PoCommandBuilder, it provides the dedicated constructor to build the Open Secure Session APDU command.

* Method: OpenSessionCmdBuild (PORevision[0..1] revision, Byte keyIndex, ByteArray samChallenge, Byte[0..1] sfiToSelect, Byte[0..1] recordNumberToRead) *throw* InconsistentCommandException
** The CalypsoCommands reference is defined with the value ‘PO_OPEN_SESSION’.
** If the *optional* revision parameter is missing, use the current PoCommandBuilder.defaultRevision. In revision 1 & 2, the class byte is set at 94h (otherwise at 00h). In revision 2, the presence of the KVC is asked.
* Method: OpenSessionCmdBuild (ApduRequest request) *throw* InconsistentCommandException
** Bytes low level constructor: throw an exception if the request’s instruction code isn’t the one defined for ‘PO_OPEN_SESSION’ CalypsoCommands’ reference, otherwise call the super constructor.

===== Class: CloseSessionCmdBuild

This class *extends* PoCommandBuilder, it provides the dedicated constructor to build the Close Secure Session APDU command.

* Method: CloseSessionCmdBuild (PoRevision[0..1] revision, Boolean ratificationAsked, ByteArray[0..1] terminalSessionSignature) *throw* InconsistentCommandException
** The CalypsoCommands reference is defined with the value ‘PO_CLOSE_SESSION’.
** If the *optional* revision parameter is missing, use the current PoCommandBuilder.defaultRevision. In revision 1 & 2, the class byte is set at 94h (otherwise at 00h).
** The *optional* parameter terminalSessionSignature could contain 4 or 8 bytes.
* Method: CloseSessionCmdBuild (ApduRequest request) *throw* InconsistentCommandException
** Bytes low level constructor: throw an exception if the request’s instruction code isn’t the one defined for ‘PO_CLOSE_SESSION’ CalypsoCommands’ reference, otherwise call the super constructor.

===== Class: ReadRecordsCmdBuild

This class *extends* PoCommandBuilder and *implements* SendableInSession, it provides the dedicated constructor to build the Read Records APDU command.

* Method: ReadRecordsCmdBuild (PoRevision[0..1] revision, Byte firstRecordNumber, Boolean readJustOneRecord, Byte[0..1] sfiToSelect, Byte expectedResponseLength) *throw* InconsistentCommandException
** The CalypsoCommands reference is defined with the value ‘PO_READ_RECORDS’.
** If the *optional* revision parameter is missing, use the current PoCommandBuilder.defaultRevision. In revision 1 & 2, the class byte is set at 94h (otherwise at 00h).
** If sfiToSelect is absent, then ask to address the current EF.
* Method: ReadRecordsCmdBuild (ApduRequest request) *throw* InconsistentCommandException
** Bytes low level constructor: throw an exception if the request’s instruction code isn’t the one defined for ‘PO_READ_RECORDS’ CalypsoCommands’ reference, otherwise call the super constructor.

===== Class: UpdateRecordCmdBuild

This class *extends* PoCommandBuilder and *implements* SendableInSession, it provides the dedicated constructor to build the Update Record APDU command.

* Method: UpdateRecordCmdBuild (PoRevision[0..1] revision, Byte recordNumber, Byte[0..1] sfiToSelect, ByteArray newRecordData) *throw* InconsistentCommandException
** The CalypsoCommands reference is defined with the value ‘PO_UPDATE_RECORD’.
** If the *optional* revision parameter is missing, use the current PoCommandBuilder.defaultRevision. In revision 1 & 2, the class byte is set at 94h (otherwise at 00h).
** If sfiToSelect is absent, then ask to address the current EF.
* Method: UpdateRecordCmdBuild (ApduRequest request) *throw* InconsistentCommandException
** Bytes low level constructor: throw an exception if the request’s instruction code isn’t the one defined for ‘PO_UPDATE_RECORD’ CalypsoCommands’ reference, otherwise call the super constructor.

==== Calypso PO responses' parsers

All these classes *extend ApduResponseParser* and are located in the package 'org.eclipse.keyple.calypso.command.po.parser'.

The constructors of all these subclasses may not have additional parameters than the super constructor of ApduResponseParser.

[cols="",]
|=======================================================================
|To study if there is an interest to optimize the structure of response parser classes in order to force this constructor scheme.
|=======================================================================

===== Class: GetDataFciRespPars

This class *extends* ApduResponseParser, it provides status code properties and the getters to access to the structured fields of FCI data from response of a Get Data ‘FCI’ response or a Select Application response.

* Method: GetDataFciRespPars(APDUResponse responseToParse)
** Call the super constructor of ApduResponseParser with these static elements of Map.

[cols=",,",options="header",]
|=======================================================================
| |*‘successful’* |*‘information’*
|6A88h |False |“Data object not found (optional mode not available).”
|6B00h |False |“P1 or P2 value not supported (<> 004Fh, 0062h, 006Fh, 00C0h, 00D0h, 0185h and 5F52h, according to available optional modes).”
|6283h |True |“Successful execution, FCI request and DF is invalidated.”
|9000h |True |“Successful execution.”
|=======================================================================

* To study, maybe for each getter, private attributes could be defined and initialized by the constructor.

* Method: ByteArray getDfName()
** Relevant only if successful
* Method: ByteArray getApplicationSerialNumber()
** Relevant only if successful
* Method: Byte getBufferSizeByte()
** Relevant only if successful
* Method: Integer getBufferSizeValue()
** Relevant only if successful
* Method: Byte getPlatformByte()
** Relevant only if successful
* Method: Byte getApplicationTypeByte()
** Relevant only if successful
* Method: Boolean isRev3Compliant()
** Relevant only if successful
* Method: Boolean isRev3_2ModeAvailable()
** Relevant only if successful & REV3 compliant
* Method: Boolean isRatificationCommandRequired()
** Relevant only if successful & REV3 compliant
* Method: Boolean hasCalypsoStoredValue()
** Relevant only if successful & REV3 compliant
* Method: Boolean hasCalypsoPin()
** Relevant only if successful & REV3 compliant
* Method: Byte getApplicationSubtypeByte()
** Relevant only if successful
* Method: Byte getSoftwareIssuerByte()
** Relevant only if successful
* Method: Byte getSoftwareVersionByte()
** Relevant only if successful
* Method: Byte getSoftwareRevisionByte()
** Relevant only if successful
* Method: Boolean isDfInvalidated()

[cols="",]
|=======================================================================
a|
To study, some getters are relevant only in case the command is successful or if the PO is revision 3 compliant, maybe a better approach could be to define two ‘inner’ classes: FciFIelds & Rev3DisctionaryData.

About the successful property, the same solution could be defined for all the subclasses of ApduResponseParser.
|=======================================================================

===== Class: PoGetChallengeRespPars

This class *extends* ApduResponseParser, it provides status code properties and the getters to access to the structured fields of a Get Challenge response.

(To be completed)

===== Class: OpenSessionRespPars

This class *extends* ApduResponseParser, it provides status code properties and the getters to access to the structured fields of an Open Secure Session response.

* Method: OpenSessionRespPars (APDUResponse responseToParse, PORevision revision)
** Static status properties map in REV3.2

[cols=",,",options="header",]
|=======================================================================
| |*‘successful’* |*‘information’*
|6700h |false |“Lc value not supported.”
|6900h |false |“Transaction Counter is 0.”
|6981h |false |“Command forbidden (read requested and current EF is a Binary file).”
|6982h |false |“Security conditions not fulfilled (PIN code not presented, encryption required).”
|6985h |false |“Access forbidden (Never access mode, Session already opened).”
|6986h |false |“Command not allowed (read requested and no current EF).”
|6A81h |false |“Wrong key index.”
|6A82h |false |“File not found.”
|6A83h |false |“Record not found (record index is above NumRec).”
|6B00h |false |“P1 or P2 value not supported (e.g. Rev.3.2 mode not supported).”
|9000h |true |“Successful execution.”
|=======================================================================

* Static status properties map in REV3.1

[cols=",,",options="header",]
|=======================================================================
| |*‘successful’* |*‘information’*
|6700h |false |“Lc value not supported.”
|6900h |false |“Transaction Counter is 0.”
|6981h |false |“Command forbidden (read requested and current EF is a Binary file).”
|6982h |false |“Security conditions not fulfilled (PIN code not presented, AES key forbidding the Revision 3 mode, encryption required).”
|6985h |false |“Access forbidden (Never access mode, Session already opened).”
|6986h |false |“Command not allowed (read requested and no current EF).”
|6A81h |false |“Wrong key index.”
|6A82h |false |“File not found.”
|6A83h |false |“Record not found (record index is above NumRec).”
|6B00h |false |“P1 or P2 value not supported.”
|9000h |true |“Successful execution.”
|=======================================================================

* Static status properties map in REV2.4

[cols=",,",options="header",]
|=======================================================================
| |*‘successful’* |*‘information’*
|6700h |false |“Lc value not supported.”
|6900h |false |“Transaction Counter is 0.”
|6981h |false |“Command forbidden (read requested and current EF is a Binary file).”
|6982h |false |“Security conditions not fulfilled (PIN code not presented, AES key forbidding the “compatibility mode, encryption required).”
|6985h |false |“Access forbidden (Never access mode, Session already opened).”
|6986h |false |“Command not allowed (read requested and no current EF).”
|6A81h |false |“Wrong key index.”
|6A82h |false |“File not found.”
|6A83h |false |“Record not found (record index is above NumRec).”
|6B00h |false |“P1 or P2 value not supported (key index incorrect, wrong P2).”
|9000h |true |“Successful execution.”
|=======================================================================

* Method: ByteArray getPoChallenge()
** Relevant only if successful
* Method: Integer getTransactionCounterValue()
** Relevant only if successful, and if REV3.2 or REV3.1.
* Method: Boolean wasRatified ()
** Relevant only if successful
* Method: Boolean isManageSecureSessionAuthorized ()
** Relevant only if successful (always false in REV2.4 & REV3.1).
* Method: Byte getSelectedKif()
** Relevant only if successful (always FFh in REV2.4).
* Method: Byte getSelectedKvc()
** Relevant only if successful.
* Method: ByteArray getRecordDataRead()
** Relevant only if successful, could be empty.

===== Class: CloseSessionRespPars

This class *extends* ApduResponseParser, it provides status code properties and the getters to access to the structured fields of a Close Secure Session response.

* Method: CloseSessionRespPars (ApduResponse responseToParse)
** Static status properties map

[cols=",,",options="header",]
|=======================================================================
| |*‘successful’* |*‘information’*
|6700h |false |“Lc value not supported (e.g. Lc=4 with a Revision 3.2 mode for Open Secure Session).”
|6B00h |false |“P1 or P2 value not supported.”
|6988h |false |“Incorrect signature.”
|6985h |false |“No session was opened.”
|9000h |true |“Successful execution.”
|=======================================================================

* Method: Boolean hasPostponedData()
** True is getPostponedData() not null
* Method: ByteArray getPostponedData()
** Relevant only if successful
* Method: ByteArray getSignatureLo()
** Relevant only if successful

===== Class: ReadRecordsRespPars

This class *extends* ApduResponseParser, it provides status code properties and the getters to access to the structured fields of a Read Records response.

* Method: ReadRecordsRespPars (ApduResponse responseToParse)
** Static status properties map

[cols=",,",options="header",]
|=======================================================================
| |*‘successful’* |*‘information’*
|6981h |false |“Command forbidden on Binary files.”
|6982h |false |“Security conditions not fulfilled (PIN code not presented, encryption required).”
|6985h |false |“Access forbidden (Never access mode, stored value log file and a stored value operation was done during the current session).”
|6986h |false |“Command not allowed (no current EF).”
|6A82h |false |“File not found.”
|6A83h |false |“Record not found (record index is 0, or above NumRec).”
|6B00h |false |“P2 value not supported.”
|6CXXh |false |“Le value incorrect”
|9000h |true |“Successful execution.”
|=======================================================================

* Method: Integer getRecordsNumber()
** Relevant only if successful
** Always ‘1’ in REV2.4.
* Method: ByteArray**[1..*]** getRecordsData()
** Relevant only if successful

===== Class: UpdateRecordRespPars

This class *extends* ApduResponseParser, it provides status code properties of an Update Record response. the Update Record APDU command. No dedicated getter is required, because it’s a ‘case 3’ APDU which
doesn’t return any data.

* Method: UpdateRecordRespPars (APDUResponse responseToParse)
** Static status properties map

[cols=",,",options="header",]
|=======================================================================
| |*‘successful’* |*‘information’*
|6400h |false |“Too many modifications in session.”
|6700h |false |“Lc value not supported.”
|6981h |false |“Command forbidden on Cyclic File when the record exists and is not record 01h, and on Binary files.”
|6982h |false |“Security conditions not fulfilled (no session, wrong key, encryption required).”
|6985h |false |“Access forbidden (Never access mode, DF is invalidated,
etc.).”
|6986h |false |“Command not allowed (no current EF).”
|6A82h |false |“File not found.”
|6A83h |false |“Record is not found (record index is 0 or above NumRec).”
|6B00h |false |“P2 value not supported.”
|9000h |true |“Successful execution.”
|=======================================================================
