////
 Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/

 All rights reserved. This program and the accompanying materials are made available under the
 terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
 available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html
////
== Reader Plugin implementation - factorization library

The 'plugin' package provides a set of abstract classes which factorize most of Reader Plugin generic processing: these classes could only be extended for the implementation of a specific plugin. Thereby the definition of a specific Reader Plugin could be limited to a simple wrapping of the Reader Driver natives commands.

*The access to elements of the 'plugin' package is forbidden for top applications based on the Keyple SE Proxy Service.*

=== Plugin processing classes

image::./img/uml-classDiagram-seProxy-FactorizedPlugin.svg[Class Diagram - SE Proxy Plugin Factorization]
////
[uml,file="../../build/images/uml-classDiagram-seProxy-FactorizedPlugin.svg"]
--
!include ../iuml/KeypleClassDiagram_SeProxy_FactorizedPlugin.iuml
--
////

[cols="1,1,2,3",options="header",]

|=======================================================================

|*Plugin processing classes* |*Extended by classes implementing* |*Conditions* |*Factorized operations*

|AbstractLoggedObservable |ReadersPlugin or ProxyReader |all a|* management of the naming,
* logging of observability operations

|AbstractObservablePlugin |ReadersPlugin |all a|* ProxyReader list management,
* name-based comparison of ReadersPlugin (required for SortedSet<ReadersPlugin>)

|AbstractThreadedObservablePlugin |ReadersPlugin |for plugins observing *SE reader configuration through a listening thread* |management of hot-plug/unplug of ProxyReader

|AbstractStaticPlugin |ReadersPlugin |for plugins with a *SE Readers static configuration* | -

|AbstractObservableReader |ProxyReader |all a|* High level logging & benchmarking of SeRequestSet transmission, & SeResponseSet reception (transmit method of ProxyReader),
* name-based comparison of ProxyReader (required for SortedSet<ProxyReader>)

|AbstractLocalReader |ProxyReader |for plugins operating *local SE readers* (normally all plugins except the Remote SE plugin) a|* Management of the loop processing for SeRequest transmission in a set and for SeResponse reception in a set
* Low level logging of ApduRequest transmission and ApduResponse reception
* Case 4 APDU hack processing (automatic send of GetResponse command in case of response missing data.
* SE logical channel state management
* SE reader protocol setting

|AbstractSelectionLocalReader |ProxyReader |for local readers requiring the set of a *Select Application* command with AID a|* SE logical channel opening & application selection through AID
* ReaderObserver list setting

|AbstractThreadedLocalReader |ProxyReader |for local readers managing *SE detection through a listening thread* |Management of the thread listening SE insertion/remove for a reader.

|=======================================================================





=== Examples of some standard reader plugin integrations

- "Remote SE Plugin": by definition, remote readers aren't managed locally; the plugin could notify in case a connection with a remote reader is established or lost.
- "PC/SC Plugin": the plugin requires to manage the selection of a specific SE application, threads are involved to listen notification of reader plug/unplug and SE insertion/remove.
- "Android NFC Plugin": the configuration is limited to a single reader that can't be removed; SE insertion are notified through Android Intent.
- "Android OMAPI": the configuration of SE contacts readers is static; SE presence is readers is managed statically too.

image::./img/uml-classDiagram-seProxy-NativePlugin.svg[Class Diagram - SE Proxy Native Plugins Integration]
////
[uml,file="../../build/images/uml-classDiagram-seProxy-NativePlugin.svg"]
--
!include ../iuml/KeypleClassDiagram_SeProxy_NativePlugin.iuml
--
////

