////
 Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/

 All rights reserved. This program and the accompanying materials are made available under the
 terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
 available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html
////
== 'Secure Element Proxy' API
=== Functional processing

image::./img/20180322-CNA-SDK-Architecture-Plugins.svg[Scheme - SE Proxy's Plugins]

The SE Proxy API must provide a common way to manage local or remote SE readers, providing a common interface to address NFC mobile environment or PC/SC compliant readers, or any proprietary drivers.

* The PC/SC API provides basic functions to list and select compliant readers, to establish a connection, and to transfer APDU commands and get the corresponding responses, one by one.
* The Smart Card IO API, used as PC/SC interface for J2SE application, provides a higher abstraction level by automatically managing 61XXh and 6CXXh warning status. In this case, the usage of the Get Response command is no longer required, ISO 7816-4 APDU command could be managed in the same way whatever the transmission protocol ISO 7816-3 T=0 or T=1, case 4 APDU commands are always processed as in contactless.
** ‘Case 4’ commands shall always be set with ’Le’ at 00h.
** ‘Case 2’ commands must not be set with a ‘Le’ value higher than the number of available bytes.
* The Open Mobile API, defined to address SE in mobile environments, adds another step of abstraction with the automatic allocation of logical channels. In this case, the Select Application command is useless; a logical channel opening is requested for a specific AID, then API performs directly the selection for the first available or the specified logical channel. The class bytes of the coming APDU commands are automatically updated for the selected logical channel.

To simplify the management of logical channels with a SE, **the SE Proxy API limits the establishment of only one logical channel at a time per SE.**

* A Calypso PO supports the selection of only one application at a time.
* A CSM HSM plugin could emulate the presence of several CSM SE.

To optimize the interfacing with remote SE readers (PO or SAM):

* The SE proxy API may manage grouped APDU commands: in order to perform operations comprised of sets of APDU requests and get the corresponding set of APDU responses through a single call. It may still be possible to emulate an APDU by APDU sequential transaction by using commands groups containing a single APDU command.
* A single SE reader call may allow to specify at once the AID of the application to select (in order to open a specific logical channel if necessary), to transmit a group of APDU commands to play, and to define the final logical channel status after the receipt of the last APDU response of the group (in order to keep the channel open or to close it).

To support revision 1.0 and 2.4 Calypso POs in contacts T=0 mode, APDU commands’ information may declare if the ISO 7816-4 APDU is a case 4. If a case 4 response misses its data bytes, the SE plugin may send a Get Response command to retrieve the missing data.

////
[NOTE]
////
[WARNING]
.Support of old Calypso products not compliant with ISO 7816-4 for ‘case 4’ APDU in contacts mode:
================================================================================
* Calypso Revision 2.4 Portable Objects and ‘S1Dx’ SAM replies on a case 4 APDU in contacts mode the successful status 9000h instead of 61XYh → in this case the Reader Plugin wouldn’t be able to automatically request a GetResponse command for a length XYh.
* To recover this, case 4 APDU could be highlighted with this ‘case 4’ flag: then in case of missing data in the response with a successful status, the plugin will have to request a GetResponse for a length 00h.
================================================================================
[WARNING]
.Plugins’ rules:
================================================================================
* On a request to transmit a set of APDU commands to a specific SE Application, the SE plugin or its lower driver must open a logical channel and select the targeted application (if not already selected) *without expecting an explicit SelectApplication command* from the SE Proxy.
* *Only one single logical channel* could be open at a time with a SE Reader.
** A smartcard reader with several physical interfaces (e.g.: several contactless antennas, or several SAM slots) => should be managed through several SE Proxy.
** For a Secure Element supporting several logical channels at a time through a physical interface: the logical channels could be managed though different SE Proxy.
================================================================================


////
[width="100%"]
|====================
a|
*Plugins’ rules:*

* On a request to transmit a set of APDU commands to a specific SE Application, the SE plugin or its lower driver must open a logical channel and select the targeted application (if not already selected) without expecting an explicit SelectApplication command from the SE Proxy.
* Only a single logical channel could be open at a time with a SE Reader.
** A smartcard reader with several physical interfaces (e.g.: several contactless antennas, or several SAM slots) => should be managed through several SE Proxy.
** For a Secure Element supporting several logical channels at a time through a physical interface: the logical channels could be managed though different SE Proxy.

|====================
////

Readers’ specific settings (e.g. contactless protocol sequences polling, communication speed, …) may be managed at the plugin level. The SE proxy API provides a generic way to push or get specific reader’s parameters.

On a terminal, the SE Proxy API could be interfaced with several plugins at a time, in order to address PO and CSM, to operate both local and remote readers, supporting both PC/SC and proprietary readers.

All the classes and interfaces defining the SE Proxy Service will be contained in the package ‘org.eclipse.keyple.seproxy’.
