////
 Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/

 All rights reserved. This program and the accompanying materials are made available under the
 terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
 available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html
////
=== SE Proxy API - for terminal application implementation

==== Access to configurable SE readers

image::./img/uml-classDiagram-seProxy-AccessReader.svg[Class Diagram - SE Proxy Reader Access]
////
[uml,file="../../build/images/uml-classDiagram-seProxy-AccessReader.svg"]
--
!include ../iuml/KeypleClassDiagram_SeProxy_Reader.iuml
--
////
The SE Proxy Service singleton is the **entry point of the SE Proxy Service**:

- its instance has to be <b>called by a ticketing application<b/> in order to establish a link with a SE’s readers.
- Different specific reader plugins could be set to the SE Proxy Service: each reader plugin is defined with a unique name.
- On the SE Proxy Service the list of Reader Plugins currently set could be recovered sort by plugin name.

ReadersPlugin is the generic interface to manage drivers of SE reader (PC/SC, NFC Android, ...):

- For a specific reader plugin, different SE readers could be available: each reader of a plugin is defined with a unique name.
- The list of available SE readers could be recovered sort by reader name.

ProxyReader is the generic interface to manage SE readers:

- A SE reader provides the possibility to check is a SE is present in the reader.
- By defining some specific SE protocols' settings, we could configure a reader to recognize the communication protocol (contacts: ISO 7816-3, contactless: ISO 14443-4, B', Mifare, ...) of the targeted SE.
- Some set of SE requests, containing APDU commands to operate, could be transmit to reader, in order to get the corresponding response, according to SE present in the reader.

Plugins & SE readers could require the setting of specific parameters.

==== APDU command transmission
image::./img/uml-classDiagram-seProxy-TransmitApdu.svg[Class Diagram - SE Proxy APDU Transmission]
////
[uml,file="../../build/images/uml-classDiagram-seProxy-TransmitApdu.svg"]
--
!include ../iuml/KeypleClassDiagram_SeProxy_Apdu.iuml
--
////

A SE Request aggregates the elements to open a logical channel with a SE and select a SE application, and group of APDU to exchange with the selected application.

* When defining an optional protocol flag to a SE Request, the reader will try to operate the request only if the SE communication protocol matches the flag.
* For SE application requiring an explicit selection: an AID should be defined in the SE Request (through an AidSelector), in this case the reader build and transmit the right Select Application.
* The grouping of APDU command requests in a SE request allows to optimize the network messages in case the reader is remote to the terminal.
* After the processing of a SE Request a reader automatically close the logical channel with the SE application: except if the SE request explicitly ask to keep it open.

A terminal could accept on a reader several kinds of SE applications: those applications could be selected through different AID and could be based on different SE protocol.
Depending on the kind of SE applications set as supported on a reader: the transmission of a set of SE requests could be requested.

* The SE requests of a set are processed sequentially.
** If the protocol flag of a SE request matches the SE protocols defined for the reader, then the reader tries to open a logical channel.
** A non-matching SE request is skipped.
* For a specific SE request, if a logical is opened, the included APDU commands are transmitted to the selected application.
** In case the SE request is defined to keep the logical channel open, the processing of the SE request set stops even if there are remaining SE requests with SE protocol flags matching the reader setting.
** Otherwise, if the logical channel could be closed after the APDU transmission:
*** The reader processes the next pending SE request matching the reader protocol settings.
*** If there is no more SE request to process, and no logical channel to maintain, then the reader could finally close the physical channel with the SE.

By defining an APDU request with a 'case 4' flag, in case SE application doesn't reply data: the reader is in charge to transmit a Get Response in order to recover the response. This 'hack' allows to support SE not fully compliant with ISO 7816-4 for case 4 APDU commands (e.g. as for the first generation of Calypso revision 1 native SE).
For an APDU request, the optional setting of successful status code other that 0x9000 allows the reader to identify is a corresponding APDU response is successful.

In a SE response, at least one between the ATR field & the FCI should be non-null:

* A SE application explicitly selected with an AID may provide FCI data.
* A SE application implicitly selected is generally identified with the ATR of the SE.

==== Notification of plugin & reader events

image::./img/uml-classDiagram-seProxy-Event.svg[Class Diagram - SE Proxy Reader Event]
////
[uml,file="../../build/images/uml-classDiagram-seProxy-Event.svg"]
--
!include ../iuml/KeypleClassDiagram_SeProxy_Event.iuml
--
////
To be notified on plugin events (hot-plug / unplug of some readers) & reader events (insertion / remove of a SE in a specific reader), a terminal application could respectively implement interfaces of Plugin Observer or Reader Observer.

* Observers could be defined for a specific plugin or a reader.
* In case of status change, an observable plugin or reader will notify its observers.
 
 
 
