////
 Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/

 All rights reserved. This program and the accompanying materials are made available under the
 terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
 available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html
////
== 'Generic Command' API

The 'Commands' module is the base to define the APDU commands’ sets for a specific Secure Element application. All these commands could be operated independently in *standalone*.

To manage SE commands, the library requires:

* functions to *build* APDU requests in order to generate the arrays of bytes to send to a SE in a group of APDU requests (SeRequestElement),
* and functions to *parse* the arrays of bytes replied by the SE in a group of APDU responses (SeResponseElement).

image::./img/uml-classDiagram-commands-GenericTable.svg[Class Diagram - SE Proxy Generic Commands Table]
////
[uml,file="../../build/images/uml-classDiagram-commands-GenericTable.svg"]
--
!include ../iuml/KeypleClassDiagram_Command_Archi.iuml
--
////

=== Interface: CommandsTable

This interface allows to define a register of Commands’ Sets including association between Commands’ Builders and Responses’ Parsers. It provides the generic getters to retrieve: the name & the instruction byte of a command, and the corresponding ApduCommandBuilder & ApduResponseParser classes.

* Method: String getName()
** returns the command name.
* Method: Byte getInstructionByte()
** returns the value of the INS byte.
* Method: Class getCommandBuilderClass()
** returns the Command Builder class.
* Method: Class getResponseParserClass()
** returns the Response Parser class.

=== abstract Class: ApduCommandBuilder

This *abstract* class has to be *extended by all SE command builder classes*, it provides the generic getters to retrieve: the name of the command, the built ApduRequest, the corresponding ApduResponseParser class.

* *private* Attribute: CommandsTable commandReference
** the reference of the command in the matrix array enumeration, in order to get the name and the response parser class of the command.
* *private* Attribute: ApduRequest request
** the byte array APDU request.
** *For ‘case 4’ APDU command, the ‘Le’ field shall be present with the value 00h.*
* *abstract* Method: ApduCommandBuilder(CommandsTable reference, ApduRequest request)
** the generic abstract constructor to build an APDU request with a command reference and a byte array.

* *final* Method: String getName()
** returns the name of the APDU command from the CommandsTable information.
* *final* Method: ApduRequest getApduRequest()
** returns the APDU request.
* *final* Method: Class getApduResponseParserClass()
** returns the corresponding ApduResponseParser class of the APDU command from the CommandsTable information.

=== abstract Class: ApduResponseParser

This *abstract* class has to be *extended by all SE response parser classes*, it provides the generic getters to manage response’s status.

* *private* Attribute: ApduUResponse response
** the byte array APDU response.
* *protected* inner Class (or struct) StatusProperties
** *protected* Attribute: Boolean successful
** *protected* Attribute: String information
* *protected* Attribute: Map<Short, StatusProperties>: statusTable
** A map with the double byte of a status as key, and the successful property and ASCII text information as data.
* *abstract* Method: ApduResponseParser(ApduResponse responseToParse, Map<Short, StatusProperties>)
** the generic abstract constructor to build a parser of the APDU response, it sets the ApduResponse and the Map of StatusProperties pushed by the sub-classes.

* *final* Method: ApduResponse getApduResponse ()
** returns the ApduResponse instance.
* *final* Method: Short (or unsigned short) getStatusCode)
** Returns SW1-SW2 bytes from the ApduResponse.
* *final* Method: Boolean isSuccessful()
** Returns if the status is successful from the statusTable according to the current status code.
* *final* Method: String getStatusInformation()
** Returns the ASCII message from the statusTable for the current status code.

