////
 Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/

 All rights reserved. This program and the accompanying materials are made available under the
 terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
 available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html
////
== Global architecture
The Keyple SDK is divided in two major layers:

* The ‘Secure Element Proxy API’ which allows to manage SE readers in a generic way.
* The ‘Calypso Processing API’ which contains at least the full sets of commands for Calypso Portable Object and Security Module, and the macro commands to manage secure Calypso transactions. This module could also be extended with features to support the Hoplink application.

image::./img/20180322-CNA-SDK-Architecture-GlobalArch.svg[Scheme - Global Architecture]

Dedicated reader’s plugins have to be implemented in order to interface the SE Proxy API with the specific reader’s drivers.
