' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' All rights reserved. This program and the accompanying materials are made available under the
' terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
' available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html

package org.eclipse.keyple.seproxy.plugin #FFFFFF {

abstract AbstractStaticPlugin
abstract AbstractThreadedObservablePlugin
abstract AbstractObservableReader
abstract AbstractLocalReader
abstract AbstractSelectionLocalReader
abstract AbstractThreadedLocalReader

''!include ./KeypleClassDiagram_SeProxy_Elements.iuml!OBSERVABLE_PATTERN
''!include ./KeypleClassDiagram_SeProxy_Elements.iuml!OBSERVABLE_LOG
'!include ./KeypleClassDiagram_SeProxy_Elements.iuml!OBSERVABLE_PLUGIN
'!include ./KeypleClassDiagram_SeProxy_Elements.iuml!OBSERVABLE_READER
'!include ./KeypleClassDiagram_SeProxy_Elements.iuml!FACTORIZE_EVENT_PLUGIN
'!include ./KeypleClassDiagram_SeProxy_Elements.iuml!FACTORIZE_EVENT_READER
'
'hide AbstractPluginEvent
'hide ErrorPluginEvent
'hide ReaderPresencePluginEvent
'hide ReaderEvent
'hide Observer_PluginEvent
'hide Observer_ReaderEvent
'hide AbstractLoggedObservable
'hide AbstractLoggedObservable_PluginEvent
'hide AbstractLoggedObservable_ReaderEvent
'hide AbstractObservablePlugin
'hide PluginObserver
'hide ReaderObserver
'hide AbstractEventThread
'hide EventThread_Plugin

AbstractThreadedObservablePlugin -right[hidden]-> AbstractObservableReader
AbstractObservableReader -down[hidden]->AbstractStaticPlugin

'!include ./KeypleClassDiagram_SeProxy_Elements.iuml!FACTORIZE_LOCAL_READER
'hide EventThread_Reader

AbstractThreadedLocalReader -down[hidden]-> AbstractLocalReader
AbstractThreadedLocalReader --|> AbstractSelectionLocalReader
AbstractLocalReader <|-right- AbstractSelectionLocalReader : extends
}

'AbstractObservableReader -down[hidden]-> AbstractLocalReader

'AbstractObservableReader <|-left- AbstractLocalReader : extends
'AbstractLocalReader -right-|> AbstractObservableReader : extends'
'AbstractObservableReader <|-right- AbstractLocalReader : extends
AbstractObservableReader <|-- AbstractLocalReader : extends
AbstractObservableReader -right[hidden]-> AbstractThreadedLocalReader


!include ./KeypleClassDiagram_SeProxy_Elements.iuml!INTERNAL_PLUGIN


RemoteSePlugin -down-|> AbstractThreadedObservablePlugin : extends
RemoteSeReader -down-|> AbstractObservableReader : extends

PcscPlugin -down-|> AbstractThreadedObservablePlugin : extends
PcscReader -down-|> AbstractThreadedLocalReader : extends

AndroidOmapiPlugin -up-|> AbstractStaticPlugin : extends
AndroidOmapiReader -up-|> AbstractLocalReader : extends

AndroidNfcPlugin -up-|> AbstractStaticPlugin : extends
AndroidNfcReader -up-|> AbstractSelectionLocalReader : extends






