' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' All rights reserved. This program and the accompanying materials are made available under the
' terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
' available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html

package org.eclipse.keyple #FFFFFF {

package seproxy #FFFFFF {

!include ./KeypleClassDiagram_SeProxy_Elements.iuml!PROXY_INTERFACE
hide ReadersPlugin
!include ./KeypleClassDiagram_SeProxy_Elements.iuml!SE_REQUEST_SET
!include ./KeypleClassDiagram_SeProxy_Elements.iuml!APDU_REQUEST
!include ./KeypleClassDiagram_SeProxy_Elements.iuml!APDU_STRUCTURE


note bottom of ProxyReader
  - To operate the transmission of SeRequestSet,
  a specific <b>local</b> reader processes
  the sorted list of SeRequest.
  - According to SeRequest protocolFlag and
  to the current status of the reader (RF
  protocol involved / current ATR) the
  processing of a specific SeRequest could be
  skipped.
  - When processing a SeRequest
    o if necessary a new logical channel is
    open (for a specific AID if defined)
    o and ApduRequest are transmited one by
    one
end note

note top of SeRequestSet
 - A SeRequestSet could contain several SeRequest to manage the selection
 of different types of PO application.
 - To exchange APDU commands with a soecific selected PO application
 a single SeRequest is necessary.
end note

note top of SeRequest
 - For PO requiring an AID selection, the aidToSelect should be defined
 with non null value. For PO not supporting AID selection, the aidToSelect
 should be defined as null.
 - The protocolFlag parameter is optional.
end note
}

package util #FFFFFF {
  class ByteBufferUtils {
    +{static}ByteBuffer fromHex(String hex)
    +{static}String toHex(ByteBuffer buffer)
    +{static}String toHex(List<ByteBuffer> buffers)
    +{static}String toHex(ByteBuffer... buffers)
    +{static}String toHexCutLen(ByteBuffer buffer, int... cutLength)
    +{static}byte[] toBytes(ByteBuffer buffer)
    +{static}ByteBuffer subIndex(ByteBuffer buf, int start, int end)
    +{static}ByteBuffer subLen(ByteBuffer buf, int offset, int length)
    +{static}ByteBuffer concat(ByteBuffer buf1, ByteBuffer buf2)
    
  }
}
}

together {
  interface SeProtocol
  enum ContactlessProtocols
  enum ContactsProtocols
  interface ProxyReader
  abstract AbstractApduBuffer
  class ApduRequest
  class ApduResponse
  class SeRequest
  class SeRequestSet
  class SeResponse
  class SeResponseSet
}

'org.eclipse.keyple.util -down[hidden]- org.eclipse.keyple.seproxy

'external.terminalapplication .up.> org.eclipse.keyple.seproxy : imports

'SpecificTerminal --> SeProxyService : uses >

'SeProxyService "1" *-down-> "*" ReadersPlugin : plugins
'ReadersPlugin "1" *-right-> "*" ProxyReader : readers

'SeProxyService -right[hidden]- SeRequestSet
ProxyReader -up- SeRequestSet : sends >
ProxyReader -down- SeResponseSet : receives >

SeRequestSet "0..1" o-right-> "+" SeRequest : sortedSeRequests
SeRequest "0..1" o-down-> "*" ApduRequest : apduRequests

ApduRequest -down-|> AbstractApduBuffer : extends
ApduResponse -up-|> AbstractApduBuffer : extends

SeResponse "0..1" o-up-> "*" ApduResponse : apduResponses
SeResponseSet "0..1" o-right-> "+" SeResponse : seResponses

SeRequest +-right- Selector
Selector <|-up- AidSelector : extends
Selector <|-down- AtrSelector : extends

SeProtocol <|-- ContactlessProtocols : extends
SeProtocol <|-- ContactsProtocols : extends
ContactsProtocols -left[hidden]- ContactlessProtocols

SeRequest -- SeProtocol : SE Protocol Flag
ProxyReader -right- SeProtocol : SE Protocol Settings
SeProtocol -right[hidden]- ApduRequest
SeResponse -down[hidden]- ByteBufferUtils

