' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' All rights reserved. This program and the accompanying materials are made available under the
' terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
' available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html

!include ./KeypleClassDiagram_SeProxy_Elements.iuml!TERMINAL_LIGHT

package org.eclipse.keyple.seproxy #FFFFFF {
!include ./KeypleClassDiagram_SeProxy_Elements.iuml!SERVICE
!include ./KeypleClassDiagram_SeProxy_Elements.iuml!PROXY_INTERFACE

package util #FFFFFF {
!include ./KeypleClassDiagram_SeProxy_Elements.iuml!NAMEABLE_CONFIGURABLE
}

note " - Must be extended only by\n<b>singleton</b> classes\n - ProxyReader elements are\nunique." as N1


note "For implementation classes, the visibility\nof the constructor should be defined as\n<b>proctected</b> to restrict calls by the\ncorresponding ReadersPlugin." as N2
}

!include ./KeypleClassDiagram_SeProxy_Elements.iuml!COMPARABLE

'org.eclipse.keyple.seproxy ..> java.util : imports
'external.terminalapplication ..> org.eclipse.keyple.seproxy : imports

SpecificTerminal -down-> SeProxyService : uses >

SeProxyService "1" *-down-> "*" ReadersPlugin : plugins
ReadersPlugin "1" *-right-> "*" ProxyReader : readers

NameableConfigurable <|-- ReadersPlugin : extends
NameableConfigurable <|-up- ProxyReader : extends
Comparable <|-up- ReadersPlugin : extends
Comparable <|-- ProxyReader : extends

ReadersPlugin .. N1
ProxyReader .up. N2





