' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' All rights reserved. This program and the accompanying materials are made available under the
' terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
' available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html

package org.eclipse.keyple.seproxy #FFFFFF {

package "event" as event_observer #FFFFFF {
interface PluginObserver
interface ReaderObserver
}

package plugin #FFFFFF {
	
!include ./KeypleClassDiagram_SeProxy_Elements.iuml!OBSERVABLE_PATTERN
!include ./KeypleClassDiagram_SeProxy_Elements.iuml!OBSERVABLE_LOG
'!include ./KeypleClassDiagram_SeProxy_Elements.iuml!OBSERVABLE_PLUGIN
'!include ./KeypleClassDiagram_SeProxy_Elements.iuml!OBSERVABLE_READER

!include ./KeypleClassDiagram_SeProxy_Elements.iuml!FACTORIZE_EVENT_PLUGIN
!include ./KeypleClassDiagram_SeProxy_Elements.iuml!FACTORIZE_EVENT_READER
!include ./KeypleClassDiagram_SeProxy_Elements.iuml!FACTORIZE_PLUGIN

Observer -up- Observer_PluginEvent
'Observer -left- Observer_PluginEvent
'Observer_PluginEvent -right- Observer
PluginObserver -down-|> Observer_PluginEvent : extends
Observer -up- Observer_ReaderEvent
'Observer -right- Observer_ReaderEvent
ReaderObserver -down-|> Observer_ReaderEvent : extends

AbstractLoggedObservable_PluginEvent -right[hidden]--> AbstractLoggedObservable_ReaderEvent
AbstractObservablePlugin -right[hidden]--> AbstractObservableReader


AbstractObservablePlugin <|-down- AbstractThreadedObservablePlugin : extends
'AbstractThreadedObservablePlugin -left-|> AbstractObservablePlugin : extends

'AbstractThreadedObservablePlugin -right-|> AbstractObservablePlugin : extends
'AbstractObservablePlugin <|-left- AbstractThreadedObservablePlugin : extends
'AbstractObservablePlugin <|-- AbstractThreadedObservablePlugin : extends


'AbstractThreadedObservablePlugin +-- EventThread_Plugin
AbstractThreadedObservablePlugin +-right- EventThread_Plugin
'AbstractThreadedObservablePlugin +-down- EventThread_Plugin
'EventThread_Plugin -up-+ AbstractThreadedObservablePlugin
'EventThread_Plugin --+ AbstractThreadedObservablePlugin
'EventThread_Plugin --|> AbstractEventThread : extends
EventThread_Plugin -right-|> AbstractEventThread : extends


AbstractStaticPlugin -right-|> AbstractObservablePlugin : extends
'AbstractStaticPlugin -up-|> AbstractObservablePlugin : extends
'AbstractStaticPlugin -down[hidden]--> AbstractThreadedObservablePlugin
'AbstractThreadedObservablePlugin -down[hidden]--> AbstractStaticPlugin


!include ./KeypleClassDiagram_SeProxy_Elements.iuml!FACTORIZE_LOCAL_READER

AbstractLocalReader <|-down- AbstractSelectionLocalReader : extends
'AbstractThreadedLocalReader --|> AbstractSelectionLocalReader: extends
AbstractThreadedLocalReader -right-|> AbstractSelectionLocalReader: extends
'AbstractThreadedLocalReader -up-|> AbstractSelectionLocalReader: extends

'AbstractLocalReader -down[hidden]-> AbstractThreadedLocalReader
'AbstractThreadedLocalReader -down[hidden]-> AbstractLocalReader

'AbstractThreadedLocalReader +-- EventThread_Reader
AbstractThreadedLocalReader +-left- EventThread_Reader
'AbstractThreadedLocalReader +-down- EventThread_Reader
'EventThread_Reader -up-+ AbstractThreadedLocalReader
'EventThread_Reader --+ AbstractThreadedLocalReader
'EventThread_Reader -down-+ AbstractThreadedLocalReader
'AbstractEventThread <|-- EventThread_Reader : extends
AbstractEventThread <|-right- EventThread_Reader : extends


AbstractObservableReader <|-right- AbstractLocalReader : extends
'AbstractObservableReader <|-down- AbstractLocalReader : extends

}


package "event" as event_observable #FFFFFF {
interface ObservablePlugin
interface ObservableReader
}

AbstractThreadedObservablePlugin .down.|> ObservablePlugin : implements
AbstractSelectionLocalReader .down.|> ObservableReader : implements

'!include ./KeypleClassDiagram_SeProxy_Elements.iuml!PROXY_INTERFACE
'ReadersPlugin "1" *-right-> "*" ProxyReader : readers
'
''AbstractObservablePlugin .down.|> ReadersPlugin : implements
''AbstractObservableReader .down.|> ProxyReader : implements
'AbstractObservablePlugin ..|> ReadersPlugin : implements
'AbstractObservableReader ..|> ProxyReader : implements

}

'!include ./KeypleClassDiagram_SeProxy_Elements.iuml!EXTERNAL_PLUGIN
'NativePlugin .up.|> ReadersPlugin : implements
'NativeReader .up.|> ProxyReader : implements
