' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' All rights reserved. This program and the accompanying materials are made available under the
' terms of the Eclipse Public License version 2.0 which accompanies this distribution, and is
' available at https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html

!include ../iuml/KeypleClassDiagram_SeProxy_Elements.iuml!APDU_PACKAGE
!include ../iuml/KeypleClassDiagram_Command_Elements.iuml

AbstractApduCommandBuilder "+1" o-down-> "1" ApduRequest : apduRequest
AbstractApduResponseParser "+1" o-down-> "1" ApduResponse : apduResponse
